# serene v5.3.1
#
# - docs: https://github.com/isunjn/serene/blob/latest/USAGE.md
# - check for updates: https://github.com/isunjn/serene/releases
#
#=========================================================================================


# The URL the site will be built for
base_url = "https://hoochlef.github.io"

title = "hochlef"

description = "Building smart software with Python and machine learning. Explore my projects, thoughts, and technical deep dives."

default_language = "en"

theme = "serene"

output_dir = "public"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

minify_html = false # Keep this false, as it may cause issues with some styles

build_search_index = false # Keep this false, search is temporarily unsupported

generate_feeds = true # Whether to generate a feed file in root, read docs for more info about rss feed

feed_filenames = ["feed.xml"] # "feed.xml" | "atom.xml" | "rss.xml", read docs for more info

taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]

highlight_code = true

highlight_theme = "css"

extra_syntaxes_and_themes = ["themes/serene/highlight_themes"]

highlight_themes_css = [
  { theme = "serene-light", filename = "hl-light.css" },
  { theme = "serene-dark", filename = "hl-dark.css" },
]

render_emoji = false

external_links_target_blank = true

external_links_no_follow = true

external_links_no_referrer = true

smart_punctuation = false

[slugify]
paths = "on"

taxonomies = "on"

anchors = "on"

#=========================================================================================

[extra]
sections = [
  { name = "projects", path = "/projects", is_external = false },
  # { name = "about", path = "/about", is_external = false },
  # { name = "resume", path = "/resume.pdf", is_external = true },
  { name = "[now]", path = "/now", is_external = false },
  { name = "[blog]", path = "/blog", is_external = false },
]

blog_section_path = "/blog"

back_link_text = "Back" # Text of the back button
force_theme = false # or "light" or "dark"

footer_copyright = "© 2025 or something"
footer_credits = true # Whether to show "Built with zola and serene" in footer

not_found_error_text = "404 - It’s gone. Forever. Just like your childhood dreams."
not_found_recover_text = "« go home now »"

reaction = false # Whether to enable anonymous emoji reactions (Note: You need to set up a working api endpoint to enable this feature)
reaction_align = "right" # "left" | "center" | "right"
reaction_endpoint = "https://example.com/api/reaction"
