[[collection]]
type = "card"
title = "medtrack ~ In progress"
# link = "https://github.com/aminehochlef/business-reviews-webapp"
content = "Upload a picture of a medication and get the essential information instantly."
tags = ["Django", "SQLite"]

[[collection]]
type = "card"
title = "Rato"
link = "https://github.com/aminehochlef/business-reviews-webapp"
content = "A multi-category business review platform built with FastAPI, SQLModel, PostgreSQL, and Next.js, featuring role-based access and AI integration via Hugging Face’s Mistral LLM. The system enables admins to moderate offensive reviews, supervisors to classify review urgency, and users to generate AI-powered business summaries—streamlining feedback management across diverse industries."
tags = ["FastAPI", "PostgreSQL", "Next.js", "SQLModel", "Hugging Face"]

[[collection]]
type = "card"
title = "Analysy"
link = "https://github.com/aminehochlef/Analysy-email-analyser"
content = "Analysy is a web application built using Angular and Python that provides a convenient interface for managing and visualizing email data. It leverages natural language processing libraries to analyze the content of emails, extract insights, and uncover patterns that go beyond basic metadata."
tags = ["Angular", "Flask", "NLP"]

[[collection]]
type = "card"
title = "Hangman with Pygame"
link = "https://github.com/aminehochlef/Hangman-Python"
content = "Recreated the classic Hangman game using Python and the Pygame library. This project focused on implementing game logic, keyboard input handling, and rendering a responsive graphical interface. It served as a hands-on exercise in event-driven programming and working with 2D game development concepts in Python."
tags = ["Pygame", "Python", "game-dev"]

[[collection]]
type = "card"
title = "Exploring NASA through APIs"
link = "https://github.com/aminehochlef/nasa-api-webapp"
content = "A small exploratory project built to gain hands-on experience with Spring Boot. This application consumes NASA’s public APIs to fetch and display real-time space data such as astronomy pictures, planetary information, and mission details. It served as a practical introduction to RESTful service integration, dependency management, and backend development in the Java ecosystem."
tags = ["Spring Boot", "Java", "RESTful"]

